version: '2.1'
services:
  # --> By default, this file will launch a Password Pusher instance with an
  # ephemeral (temporary) database of SQLite3.  The database will be lost on
  # restart.  If you want a persistent database, enable one of databases below.
  #
  # Uncomment to add a PostgreSQL service
  #
  # postgres:
  #   image: docker.io/postgres:15
  #   volumes:
  #     - /var/lib/postgresql/data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: pwpush_user
  #     POSTGRES_PASSWORD: pwpush_passwd
  #     POSTGRES_DB: pwpush_db
    postgres:
      image: docker.io/postgres:15
      volumes:
        - /var/lib/postgresql/data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: pwpush_user
        POSTGRES_PASSWORD: pwpush_passwd
        POSTGRES_DB: pwpush_db

  # Uncomment to add a MySQL service
  #
@@ -56,24 +56,24 @@ services:
    # the line.  This is a YAML file: indentation & spacing are critical
    #
    # depends_on:
      # - postgres  # Uncomment to use PostgreSQL
        - postgres  # Uncomment to use PostgreSQL
      # - mysql     # Uncomment to use MySQL
      # - mariadb   # Uncomment to use MariaDB
    # links:
      # - postgres:postgres # Uncomment to use PostgreSQL
        - postgres:postgres # Uncomment to use PostgreSQL
      # - mysql:mysql       # Uncomment to use MySQL
      # - mariadb:mariadb   # Uncomment to use MariaDB
    environment:
      # **--> !! If using postgres, mysql or mariadb, enable the appropriate line !! <--**
      #
      # --> Uncomment to use PostgreSQL
      # DATABASE_URL: 'postgres://pwpush_user:pwpush_passwd@postgres:5432/pwpush_db'
      DATABASE_URL: 'postgres://pwpush_user:pwpush_passwd@postgres:5432/pwpush_db'
      #
      # --> Uncomment to use MySQL or MariaDB
      # DATABASE_URL: 'mysql2://pwpush_user:pwpush_passwd@mysql:3306/pwpush_db'
      #
      # --> Uncomment to use SQLite3 (ephemeral) db that will be lost on container restart
      DATABASE_URL: "sqlite3:db/db.sqlite3"
      # DATABASE_URL: "sqlite3:db/db.sqlite3"
      #
      ################################################################################################
      # You can set other environment variables here, or in a env file.  See:
@@ -105,7 +105,23 @@ volumes:
# https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md
#
# Uncomment the following lines to set environment variables and add your own.
# environment:
environment:
	DATABASE_URL: 'postgres://passwordpusher_user:passwordpusher_passwd@postgres:5432/passwordpusher_db'
	PWP_TIMEZONE: "US/Central"
	PWP_SHOW_VERSION: false
	PWP_PW_EXPIRE_AFTER_DAYS_MAX: 7
	PWP_PW_EXPIRE_AFTER_VIEWS_MAX: 3
	PWP_PW_EXPIRE_AFTER_VIEWS_DEFAULT: 3
	PWP_PW_ENABLE_DELETABLE_PUSHES: true
	PWP_ENABLE_LOGINS: true
	PWP_ALLOW_ANONYMOUS: false
	PWP_MAIL_SMTP_AUTHENTICATION: "login"
	PWP_HOST_DOMAIN: "pwpush.com"
	PWP_MAIL_MAILER_SENDER: 
	PWP_SIGNUP_EMAIL_REGEXP: \A[^@\s]+@(domain.com)\z 
	PWP_BRAND_TITLE: "Password Pusher"
	PWP_BRAND_SHOW_FOOTER_MENU: false
	PWP_THEME: "darkly"
#   PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT: "1"
#   PWP__PW__EXPIRE_AFTER_VIEWS_MIN: "1"
#   PWP__PW__RETRIEVAL_STEP_DEFAULT: "true"
#
# Uncomment the following lines to mount a volume.
# volumes:
#   # Example of a persistent volume for the storage directory (file uploads)
#   - /path/to/directory:/opt/PasswordPusher/storage:rw
#
# Or you could override a single file in the container with a bind mount:
# volumes:
#   - type: bind
#     source: /path/to/my/custom/settings.yml
#     target: /opt/PasswordPusher/config/settings.yml
#
# To customise the application via configuration file, see settings.yml:
# https://github.com/pglombardo/PasswordPusher/blob/master/config/settings.yml
#
# Then you can use the above bind mount to overlay the file into the container on boot.
